version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kass
      POSTGRES_PASSWORD: kiisu
      POSTGRES_DB: ModuBot
    ports:
      - "5432:5432"

  chatbot:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ModuBot
      DB_USER: kass
      DB_PASSWORD: kiisu
    stdin_open: true
    tty: true
